# permissions for end users to edit frigates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: frigate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-example
    app.kubernetes.io/part-of: kubebuilder-example
    app.kubernetes.io/managed-by: kustomize
  name: frigate-editor-role
rules:
- apiGroups:
  - webapp.example.com
  resources:
  - frigates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.example.com
  resources:
  - frigates/status
  verbs:
  - get
